### ISSUE TITLE
Why I get accuracy=0 all the time?

### ISSUE THREAD

**Issue by tailuoaoteman** [fungtion/DRCN#2]

**Comment by fungtion** [comment]
https://github.com/fungtion/DRCN/blob/master/test.py#L82
Is n_correct 0?

**Comment by wogong** [comment]
@tailuoaoteman This is due to the version change of  pytorch.

you can change `accu = n_correct * 1.0 / n_total` to `accu = n_correct.item() * 1.0 / n_total` to get the expected results.

@fungtion I suggest to add the environment info to readme doc, such as pytorch version.

**Comment by fungtion** [comment]
@wogong Ok, thanks
